### ISSUE TITLE
Returned paths from git should be converted back to Windows paths

### ISSUE THREAD

**Issue by mwidmann** [ardevd/gitwrap#12]
The integration of git in Visual Studio Code (latest Insider) performs a couple commands that rely on the paths being returned as Windows paths. 

The paths returned by gitwrap are those returned by the WSL git, thus being paths inside wsl.

My Project is installed in `c:\projects\dockerfiles`. WSL is set up that `c:` is mounted as `/c` through `/etc/wsl.conf`.

When i open the folder in VScode with gitwrap set up as the `git.path` in the settings, the editor recognizes that it is a git repository and calls the following command:

`gitwrap rev-parse --show-toplevel`

This command returns `/c/projects/dockerfiles` with gitwrap, but expects `C:/projects/dockerfiles` as git for Windows would return.

**Comment by ardevd** [comment]
Thank you very much for reporting the issue and for trying Gitwrap with Visual Studio Code. I'll look into this asap.

**Comment by ardevd** [comment]
@mwidmann Could you give the attached GitWrap.exe a go and see if you find any obvious bugs with the conversion?

[GitWrap.zip](https://github.com/ardevd/gitwrap/files/2317918/GitWrap.zip)

**Comment by mwidmann** [comment]
The Zipfile can't be opened. 
```
/c/Users/mwidmann/Downloads
❯ unzip GitWrap.zip
Archive:  GitWrap.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  GitWrap.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of GitWrap.zip or
        GitWrap.zip.zip, and cannot find GitWrap.zip.ZIP, period.
```

**Comment by mwidmann** [comment]
Thank you for the new version. Had issues figuring out it was a 7z file. 

The new version still has the original issue: running `c:\tools\wsl\GitWrap.exe rev-parse --show-toplevel` in `C:\projects\dockerfiles` returns `/c/projects/dockerfiles`

**Comment by ardevd** [comment]
Hmm, that's strange. When I run it from` C:\Users\user\src\gitwrap` it looks like this:

```
GitWrap.exe rev-parse --show-toplevel
C:\Users\user\src\gitwrap
```

Ill try to replicate your folder structure and see if I can reproduce the issue.

**Comment by mwidmann** [comment]
Could it be that `C:` is not mounted to `/mnt/c` but to `/c` through the [wsl config](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#set-wsl-launch-settings)?

**Comment by ardevd** [comment]
@mwidmann That's most likely the case indeed. Hmm, I'm not entirely sure how to handle variable mount points to be honest.

**Comment by mwidmann** [comment]
There's a tool introduced in 1803 in wsl called `wslpath`. See the interoperability topic in  [What’s new for the Command Line in Windows 10 version 1803](https://blogs.msdn.microsoft.com/commandline/2018/03/07/windows10v1803/).

Maybe you could run the command `wslpath -u c:\\` once and then cache the returned value somewhere and use that instead of a hardcoded `/mnt/c`.

**Comment by ardevd** [comment]
@mwidmann Awesome. I'll look into it! Sounds like a viable solution.

**Comment by ardevd** [comment]
@mwidmann Hello again!

Could you try the attached build and see if it works?

Before you use it, please run the following from cmd if your mount point is still `/`.

`GitWrap.exe --setWslPath / `

Then see if it works

`0b1e9c9c6a115d3a9f80821bf76980806c745888d7c4941f81f9edd916340b6e  GitWrap.zip`

You can verify the test path with `GitWrap.exe --getWslPath`

[GitWrap.zip](https://github.com/ardevd/gitwrap/files/2372129/GitWrap.zip)

**Comment by mwidmann** [comment]
Hmmmm, somehow it doesn't seem to work. The WSL Path is not stored somehow. The two commands are run directly one after the other.

```
C:\projects\docker-base-images>c:\tools\wsl\GitWrap.exe --setWslPath /
[*] wslPath set to: /
C:\projects\docker-base-images>c:\tools\wsl\GitWrap.exe --getWslPath
[*] Current wslPath: /mnt/
```

**Comment by ardevd** [comment]
@mwidmann Thanks for testing. I'm retarded and forgot to call `Properties.Settings.Default.Save();`. 

I have attached a new version.

2a4b24583d462eeb7ef61b63969a2804dc5046dbe50e4c9f13366f67c41c8c52  GitWrap_5448489025aeb94ae6a148ba3f4c33cbac6e2c80.zip

[GitWrap_5448489025aeb94ae6a148ba3f4c33cbac6e2c80.zip](https://github.com/ardevd/gitwrap/files/2374873/GitWrap_5448489025aeb94ae6a148ba3f4c33cbac6e2c80.zip)

**Comment by mwidmann** [comment]
This build works, but introduces a new issue, which could be solvable with a little bit of regular expression magic but then again could introduce a new slew of other issues. The path is now converted correctly, but every output produced by git (especially in diffs, etc.) is now escaped as well. 

I have  a `.htaccess` file with  a rewrite rule where I changed something inside. The RewriteRule is a redirect to an URL (https://...) which after running `GitWrap show HEAD:webserver/sites/.htaccess` shows as `https:\\`

Now you could add a regular expression that handles paths as WSL paths only under certain situations:

- the WslPath is the first thing in the line
- the WslPath is the first thing after either a whitespace, a colon or a semicolon
- the WslPath is not directly followed by another WslPath (`//`) 
- the WslPath identified is transformable into an existing path

Sorry to make this so complicated for you. 🙁

**Comment by ardevd** [comment]
I enjoy the challenge. It's a made tricky by the fact that you have / as your mnt point but I woke last night and thought out a simple fix for it. Now I just need to remember it ^^

**Comment by mwidmann** [comment]
Looking forward to you remembering and implementing it

**Comment by ardevd** [comment]
Thanks for taking the time to test! 

I now only convert forward slashes if the WSLPath was detected on the current line of output. I hope this might at least reduce the impact of the issues you experience but it does result in two limitations

1. Only absolute paths will be converted
2. If output from git includes both an absolute path and some other string with a / the latter will still be converted. I cant think of a situation where that might occur though but you seem more versed in obscure git commands than myself :)

Could you give the attached build a go and report back your findings and thoughts?

29d0e193318f4eb1948508bfe74fd6f6d30084940a4df20cb83652834e2f5548  GitWrap/bin/x64/Release/GitWrap_239ce0ad21fce9694ab72956d27249d901febb8e.zip

[GitWrap_239ce0ad21fce9694ab72956d27249d901febb8e.zip](https://github.com/ardevd/gitwrap/files/2378180/GitWrap_239ce0ad21fce9694ab72956d27249d901febb8e.zip)

**Comment by ardevd** [comment]
@mwidmann Have you had the chance to give it a go? :)

**Comment by mwidmann** [comment]
OMG, sorry, I completely forgot to answer. I tested it directly and it seems to work in most of the cases, but I had a very weird issue with a file diff, that I was trying since to reproduce. If I can reproduce it and it doesn't turn out to be just crappy code on my side, I'll open a new issue. This one is solved for me. Thank you kindly!

**Comment by ardevd** [comment]
Cool! Thanks for the feedback and testing!
